name: Basic-Workflow/Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo Building
        run: echo "BUILDING"
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check if file is present
        run: cat index.html
        
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to Ec2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd Static-Website
          git pull origin
          cd
          sudo cp -r Static-Website/* /var/www/html
          sudo systemctl restart nginx
